// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	esutil "github.com/elastic/go-elasticsearch/v8/esutil"
	mock "github.com/stretchr/testify/mock"
)

// BulkIndexer is an autogenerated mock type for the BulkIndexer type
type BulkIndexer struct {
	mock.Mock
}

// Add provides a mock function with given fields: _a0, _a1
func (_m *BulkIndexer) Add(_a0 context.Context, _a1 esutil.BulkIndexerItem) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, esutil.BulkIndexerItem) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with given fields: _a0
func (_m *BulkIndexer) Close(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stats provides a mock function with no fields
func (_m *BulkIndexer) Stats() esutil.BulkIndexerStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 esutil.BulkIndexerStats
	if rf, ok := ret.Get(0).(func() esutil.BulkIndexerStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(esutil.BulkIndexerStats)
	}

	return r0
}

// NewBulkIndexer creates a new instance of BulkIndexer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBulkIndexer(t interface {
	mock.TestingT
	Cleanup(func())
}) *BulkIndexer {
	mock := &BulkIndexer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
