// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	net "net"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PacketConn is an autogenerated mock type for the PacketConn type
type PacketConn struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *PacketConn) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LocalAddr provides a mock function with no fields
func (_m *PacketConn) LocalAddr() net.Addr {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LocalAddr")
	}

	var r0 net.Addr
	if rf, ok := ret.Get(0).(func() net.Addr); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Addr)
		}
	}

	return r0
}

// ReadFrom provides a mock function with given fields: p
func (_m *PacketConn) ReadFrom(p []byte) (int, net.Addr, error) {
	ret := _m.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for ReadFrom")
	}

	var r0 int
	var r1 net.Addr
	var r2 error
	if rf, ok := ret.Get(0).(func([]byte) (int, net.Addr, error)); ok {
		return rf(p)
	}
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte) net.Addr); ok {
		r1 = rf(p)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(net.Addr)
		}
	}

	if rf, ok := ret.Get(2).(func([]byte) error); ok {
		r2 = rf(p)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SetDeadline provides a mock function with given fields: t
func (_m *PacketConn) SetDeadline(t time.Time) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for SetDeadline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetReadDeadline provides a mock function with given fields: t
func (_m *PacketConn) SetReadDeadline(t time.Time) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for SetReadDeadline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetWriteDeadline provides a mock function with given fields: t
func (_m *PacketConn) SetWriteDeadline(t time.Time) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for SetWriteDeadline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Time) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteTo provides a mock function with given fields: p, addr
func (_m *PacketConn) WriteTo(p []byte, addr net.Addr) (int, error) {
	ret := _m.Called(p, addr)

	if len(ret) == 0 {
		panic("no return value specified for WriteTo")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte, net.Addr) (int, error)); ok {
		return rf(p, addr)
	}
	if rf, ok := ret.Get(0).(func([]byte, net.Addr) int); ok {
		r0 = rf(p, addr)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]byte, net.Addr) error); ok {
		r1 = rf(p, addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPacketConn creates a new instance of PacketConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPacketConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *PacketConn {
	mock := &PacketConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
